update(redis): switch from aioredis to redis library
hopeit-git/hopeit.engine pull request #142
Opened 2022-12-11 21:07 UTC by pcanto-hopeit

closes #140

2022-12-22 11:44 UTC, hopeit-git approved these changes

2022-12-22 11:44 UTC, hopeit-git commented on plugins/build/ci-static-plugins.sh
> +echo $code
I think this `echo` can be removed.

2022-12-22 11:45 UTC, hopeit-git commented
Version needs to be increased.

2022-12-22 11:46 UTC, hopeit-git requested changes
Version increase in version file is missing.

2022-12-22 11:51 UTC, leosmerling-hopeit commented
TODOs:
1) Increase engine version
2) There are still references to aioredis in https://github.com/hopeit-git/hopeit.engine/blob/master/plugins/streams/redis/setup.py
3) Check also https://github.com/hopeit-git/hopeit.engine/blob/master/plugins/storage/redis/setup.py

2023-01-12 20:37 UTC, hopeit-git approved these changes

2023-01-12 20:38 UTC, merged