deprecation(engine): event_api method remove title parameter, use summary instead
hopeit-git/hopeit.engine pull request #32
Opened 2021-03-23 20:38 UTC by pcanto-hopeit

SPEC:
Closes #26

RELEASE NOTES
Remove of `title` parameter in `event_api` method, use `summary` instead.

2021-03-23 22:48 UTC, leosmerling-hopeit approved these changes

2021-03-23 22:49 UTC, leosmerling-hopeit requested changes
Please increase version to 0.2.0 for both engine, plugins and apps.

2021-03-24 15:36 UTC, pcanto-hopeit reviewed
@leosmerling-hopeit In the engine I found that the file where the engine version is defined globally was decoupled from the package version, so I made the setup.py get the package version from the hopeit.server.version.
I also updated the simple-example and basic-auth versions and their respective tests.

2021-03-24 16:29 UTC, leosmerling-hopeit requested changes

2021-03-24 16:29 UTC, leosmerling-hopeit commented on plugins/auth/basic-auth/setup.py
> +    version="0.make qa.0",
0.2.0

2021-03-24 16:29 UTC, leosmerling-hopeit commented on engine/setup.py
> +    version=version['ENGINE_VERSION'],
:+1:

2021-03-24 16:35 UTC, pcanto-hopeit commented on plugins/auth/basic-auth/setup.py
> +    version="0.make qa.0",
fix on 7cd0cff27ef6aef597a194b6a7106fd2977bd077

2021-03-24 16:37 UTC, leosmerling-hopeit approved these changes

2021-03-24 16:38 UTC, merged