feature(plugins): moved hopeit.toolkit.storage.redis to a plugin
hopeit-git/hopeit.engine pull request #53
Opened 2021-05-09 00:15 UTC by pcanto-hopeit

MOTIVATION:
===========
Current version of hopeit.engine provides a toolkit for help easy way to access  Redis as key/value store.
Future versions of hopeit.engine will no more require `aioredis` library as dependency.

Plugins can be executed Standalone.

This plugin will be released as a python library and can be installed optionally when installing hopeit.engine with extras [redis-storage].

CHANGES ON THIS PR
===================
- [x] Move  `hopeit.toolkit.storage.redis` to a plugin: `hopeit.redis_storage`
- [ ] Adapt CI to release `redis-storage` plugin to PyPi
- [ ] Update installation instructions and tutorials

CURRENT STATUS
===============
Ready for initial testing. Backwards compatible with previous implementation (*)

*Requires change on import:
1 - Install hopeit.engine using [redis-storage] plugin extras:

```
 pip install "hopeit.engine[redis-storage]"
```

2 - Change import signature

From:
```
from hopeit.toolkit.storage.redis import RedisStorage
```
To:
```
from hopeit.redis_storage import RedisStorage
```

2021-05-09 08:47 UTC, leosmerling commented
Given that 0.2.4 and this both include small breaking chsnges, i th8nk it would be better to release as 0.3.0, so i suggest to set version to 0.3.0rc1 fir this pr.

We'll need also to port out toolkit.storage.fs to a plugin also in another PR.

2021-05-09 14:10 UTC, pcanto-hopeit commented
> Given that 0.2.4 and this both include small breaking chsnges, i th8nk it would be better to release as 0.3.0, so i suggest to set version to 0.3.0rc1 fir this pr.
> 
> We'll need also to port out toolkit.storage.fs to a plugin also in another PR.

I agree to change the version, and already prepare the [PR](https://github.com/hopeit-git/hopeit.engine/pull/54) to replace toolkit.storage.fs.
It looks like 0.3.0rc1 is just around the corner

2021-05-10 17:40 UTC, leosmerling-hopeit reviewed
Only possible missing is requirements.txt/setup.py for benchmark with dependency on this plugin.

2021-05-10 17:40 UTC, leosmerling-hopeit commented on apps/benchmark/simple-benchmark/src/simple_benchmark/query_something_redis.py
> +from hopeit.redis_storage import RedisStorage
I don't see this added to requirements.txt/seutp.py of the benchmark.

2021-05-10 17:40 UTC, leosmerling-hopeit commented on .github/workflows/hopeit-engine-pypi-publishing.yml
> +    - name: Publish plugin redis_streams on PyPI
Thank you!

2021-05-10 17:40 UTC, leosmerling-hopeit commented on plugins/storage/redis/src/hopeit/redis_storage/__init__.py
> -__all__ = ['RedisStorage']
Why removed?

2021-05-10 20:11 UTC, pcanto-hopeit commented on plugins/storage/redis/src/hopeit/redis_storage/__init__.py
> -__all__ = ['RedisStorage']
Solved in 7d431ea

2021-05-10 20:16 UTC, leosmerling-hopeit requested changes
Add entry in release-notes about this change.

2021-05-10 20:23 UTC, leosmerling-hopeit approved these changes

2021-05-10 20:26 UTC, merged